---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install mariadb packages
  package: >-
    name={{ item }}
    state=present
  with_items: "{{ mariadb_packages }}"
  register: mariadb_install_packages

- name: deploy global my.cnf
  template: >-
    src=my.cnf.j2
    dest={{ mariadb_conf_path }}
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: restart mariadb

- name: create mariadb configuration include directory
  file: >-
    path={{ mariadb_conf_include_dir }}
    state=directory
    owner=root
    group=root
    mode=0755

- name: create slow query log file
  when: mariadb_log_slow_queries_enabled
  command: >-
    creates={{ mariadb_slow_query_log_file }}
    touch {{ mariadb_slow_query_log_file }}

- name: set slow query log permissions
  when: mariadb_log_slow_queries_enabled
  file: >-
    path={{ mariadb_slow_query_log_file }}
    state=file
    owner={{ mariadb_owner }}
    group={{ mariadb_owner }}
    mode=0644

- name: deploy backup
  include_tasks: backup.yml
  when: mariadb_do_backup
  tags: backup

- name: enable and start mariadb
  service: name=mariadb enabled=yes state=started

- include: secure-install.yml

- include: databases.yml

- include: replication.yml
